### ISSUE TITLE
minimal input

### ISSUE THREAD

**Issue by jorgeboucas** [dieterich-lab/DCC#1]
minimal input for running circTest should be:
1. a circle ID
2. circle counts
3. linear counts

also, it is not clear which counts should be taken:
a. for the circle counts: backsplice junction OR backsplice +  inner circle reads? 
b. for linear counts: all reads covering the linear transcript OR total number of reads covering the backsplice junction OR ....?

**Comment by tjakobi** [comment]
This should go to the circTest repository. However, I also assume with the current circTest version the desired operation should be implemented by now.
