### ISSUE TITLE
CircCoordinates has not column labels anymore

### ISSUE THREAD

**Issue by CDieterich** [dieterich-lab/DCC#10]
head -1 CircCoordinates 
1       1223244 1223968 SDF4    2       -       exon-intron     gene,tra

CircCoordinates has not column labels anymore

**Comment by tjakobi** [comment]
Probably related to the new handling of GTF files from the old develop tree.

**Comment by tjakobi** [comment]
In addition to the missing column headers, the annotation shows slight differences. See issue #12 for further updates.
