### ISSUE TITLE
cant find 'tmp_unsortedNoChrM'

### ISSUE THREAD

**Issue by FranziMe** [dieterich-lab/DCC#33]
Hi, 
I am running DCC on an organism without an annotated mitochondrial chromosome. It does not matter if I run DCC with -M or not, it also breaks with -k and not, as well as -t and without. I tried various combinations of the flags and I always get the same error:

`Traceback (most recent call last):
  File "/beegfs/group_dv/home/FMetge/home/circRNA/DCC/version.0.4.4/DCC-0.4.4/DCC/main.py", line 782, in <module>
    main()
  File "/beegfs/group_dv/home/FMetge/home/circRNA/DCC/version.0.4.4/DCC-0.4.4/DCC/main.py", line 356, in main
    options.tmp_dir + "tmp_unsortedNoChrM")
OSError: [Errno 2] No such file or directory
`
Here are the versions of the python packages I am using 

> > > numpy.**version**
> > > '1.9.2'
> > > pysam.**version**
> > > '0.9.1'
> > > pybedtools.**version**
> > > '0.6.9'

Do you have any recommendations how to fix this?

[slurm-365873.txt](https://github.com/dieterich-lab/DCC/files/521377/slurm-365873.txt)
[DCC-2016-10-07_11-05.txt](https://github.com/dieterich-lab/DCC/files/521378/DCC-2016-10-07_11-05.txt)

**Comment by tjakobi** [comment]
Problem occurs when no `-R` (repetitive region file) is not supplied. In this case the file `tmp_unsortedWithChrM` is never created, therefore the following steps are failing regardless of the `-M` or any other flags.

**Comment by tjakobi** [comment]
`-F` has also to be specified, of course. Without `-F` none of the filtering flags is used at all.
