### ISSUE TITLE
extract the circRNA sequences using the script getcircfasta

### ISSUE THREAD

**Issue by tigerxu** [dieterich-lab/DCC#40]
Hi, 

I met a problem when using the script getcircfasta and the DCC output CircCoordinates to extract the circRNA sequences for further detection of miRNA binding sites on these sequences. The number of circRNAs detected in the DCC output CircCoordinates is not equal to the number of the circRNA sequences generated by the script getcircfasta. The command lines I used is listed below.

$ python ~/install/DCC-0.4.4/scripts/getcircfasta -f /data5/haozhang/install/refGenome/mouse/GRCm38.primary_assembly.genome.fa -c /data5/haozhang/data/JEVmouseBrain-multiOmics/circRNA/DCC/detect_circRNA/CircCoordinates -e /data5/haozhang/install/refGenome/mouse/gencode/gencode.vM14.annotation.bed -o circRNA-sequence.fa &

$ wc -l CircCoordinates
3181 CircCoordinates

$ grep -c '>' circRNA-sequence.fa
899

Any suggestion is very appreciated! Thanks!

Zhuofei

**Comment by tjakobi** [comment]
Thank you for your bug report @tigerxu. I'll look into it.

**Comment by tjakobi** [comment]
Just to catch the most simple explanation, what happens if you increase the `-m` option to, let's say 50000? The default is only 5000.

**Comment by tigerxu** [comment]
Many thnaks for your advice! It works when -m option set to 50000. More circRNA sequences are produced.
