### ISSUE TITLE
Cannot provide mate separate mapping BAMs to -B list

### ISSUE THREAD

**Issue by plmsuper8** [dieterich-lab/DCC#45]
Hi @tjakobi ,
I got a problem how to provide all 3 *Aligned*.bam files to -B list when mapping mate separately ? It kept warning "BAM file list is shorter than mate list". However, if let DCC guess which bam to use, it would only pick *.mate1.Aligned.sortedByCoord.out.bam, which seems incorrect?

Or may I just use BAMs from paired-end alignment? Thx.

**Comment by tjakobi** [comment]
Dear @plmsuper8 ,

did you specify the BAM files via `-B file1 file 1 file 3`? The easiest way would normally to have 3 files, e.g. mate1.txt, mate2.txt and bam_files.txt and have the full path to each of the files in these. 

Afterwards, you may specify `-mt1 @mate1.txt -mt2 @mate2.txt -B @bam_files.txt`  to let DCC know about the files.

Cheers
Tobias

**Comment by plmsuper8** [comment]
Hi @tjakobi,

actually I tried, my command line is as below (the DCC_merge.bamlist contains all *.mate1.Aligned, *.mate2.Aligned and *Aligned BAMs). But it didn't work.

DCC @DCC_SAMPLES.samplesheet -T 24 -O ./ \
 -Pi --filter -R ${IMASK} \
 -mt1 @DCC_MATE1.samplesheet -mt2 @/DCC_MATE2.samplesheet \
 -B @DCC_merge.bamlist \
 -D -G -ss \
 -an ${IGTF} \
 -Nr 2 5 \
 --refseq ${IGENOME}

**Comment by tjakobi** [comment]
Dear @plmsuper8,

I think the problem is that you contained all BAMs in the `DCC_merge.bamlist `. The file should only contain the non-mate BAM files, i.e. all files should have the same number of lines.

Cheers,
Tobias

**Comment by plmsuper8** [comment]
Hi Tjakobi,

Thanks for your help. it works nicely now.

Best
