### ISSUE TITLE
Dubious CircSkipJunctions output

### ISSUE THREAD

**Issue by CDieterich** [dieterich-lab/DCC#47]
I have noticed some splice junction output that does not make any sense (i.e. no supporting reads)

in /prj/circRNA_ENCODE3/workflow/DCC_CD_07_2017/CircSkipJunctions
I found
`1       26255171        26255865        0       0       0       0       0      00       0       0       0       0       0       0       1:26244319-26257596:0  00       0       0
`

**Comment by tjakobi** [comment]
I could trace back the error to the temporary count files created by DCC.
I am now rerunning the same project to generate those temporary files again for further analysis.

**Comment by CDieterich** [comment]
Did you push a fix for this problem, too ?

**Comment by tjakobi** [comment]
I need to run tests to make sure everything is working now. Code will be pushed afterwards.
