### ISSUE TITLE
CircSkipJunctions does not contain junction orientation

### ISSUE THREAD

**Issue by CDieterich** [dieterich-lab/DCC#48]
Here is another problem..

Linear Skip Junctions are reported as:
1:1257311-1273665:4

Unfortunately, it is not clear from this format if
the junction is in **Sense or antisense** to the gene locus.

Please investigate

**Comment by tjakobi** [comment]
The strand information is available via temporary count files. Including the strand is straightforward by modifying the `combine()` function of `CombineCounts.py`.
However, this will of course change the output format and may brake old downstream scripts.

**Comment by CDieterich** [comment]
Ok, we leave this for the next major release then (DCC 0.5)

**Comment by tjakobi** [comment]
Fixed by  merging of 66c4d0373a2edfb19822c5bccb18255fb1151cba
