### ISSUE TITLE
Problem during host gene expression counting

### ISSUE THREAD

**Issue by BaluPai** [dieterich-lab/DCC#51]
DCC just hangs with no response at this step (counting the host gene expression)

_Started linear gene expression counting for /home/balupai/tools/DCC-0.4.6/DCC/joint-mapping/1_hg38Aligned.sortedByCoord.out.bam        => running mpileup for start positions [/home/balupai/tools/DCC-0.4.6/DCC/joint-mapping/1_hg38Aligned.sortedByCoord.out.bam][fai_load] build FASTA index._

And this is the command that I set for the DCC..

DCC @samplesheet.txt -mt1 @mate1.txt -mt2 @mate2.txt -D -R /home/balupai/Annotations/STAR_hg38Genome/Repeats_hg38_March2018.gtf -an /home/balupai/Annotations/STAR_hg38Genome/UCSC_hg38_knownGene_2017-08.gtf -Pi -F -M -Nr 5 2 -fg -G -A /home/balupai/Annotations/STAR_hg38Genome/Genome

Thanks in advance for any suggestions

**Comment by tjakobi** [comment]
Dear @BaluPai,

thank you for reporting your issue. Just to make sure we have everything that's required, are all of the `*Aligned.sortedByCoord.out.bam` files indexed? 

Also: ` -A /home/balupai/Annotations/STAR_hg38Genome/Genome` should be the original FASTA file of the employed genome. It looks you try to pass the STAR index? 

Cheers,
Tobias

**Comment by BaluPai** [comment]
Dear @tjakobi,

Yes I have made additional .bai files for all the *Aligned.sortedByCoord.out.bam files.

And regarding the Genome.fa and the index, yes I have a folder with all the .fa and the SAindex (STAR) file in there that I provide. 
Best,
Balu

**Comment by tjakobi** [comment]
Dear @BaluPai,

thank you for your reply. What file is `/home/balupai/Annotations/STAR_hg38Genome/Genome` exactly? `-A` should be a FASTA file, not a directory or an index. 

Something like `-A /path/to/genome.fasta`

Cheers,
Tobias

**Comment by BaluPai** [comment]
Dear @tjakobi,

Yes it is a Fasta file...

Regards,
Balu

**Comment by tjakobi** [comment]
Dear @BaluPai,

what samtools version are you currently using? You may have to generate a FASTA index first via `samtools faidx /home/balupai/Annotations/STAR_hg38Genome/Genome`.

Cheers,
Tobias

**Comment by BaluPai** [comment]
Dear @tjakobi,
I guess it helped to Index the Genome.Fa separately again,And now it works all fine.

Thanks for the input.
Cheers,
Balu
