### ISSUE TITLE
the "circRNA read counts" in output file

### ISSUE THREAD

**Issue by circR** [dieterich-lab/DCC#54]
Hi Sir

Does the "circRNA read counts" in the output file represent the "back-splicing junction reads" or the total reads that mapped to the predicted circRNA region? 
If it's the latter, is there a way to get the junction reads only?
Thank you very much.

**Comment by tjakobi** [comment]
Dear @circR,

thank you for your feedback. 

The circRNA read counts refer to the back splicing read counts. 

More details about the detection process can also be found in the [paper](https://academic.oup.com/bioinformatics/article/32/7/1094/1743588)  and the [supplementary material](https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/bioinformatics/32/7/10.1093_bioinformatics_btv656/3/btv656_Supplementary_Data.zip?Expires=2147483647&Signature=ldBn65WvhzV9owoeNjdggBEDas019bPg8PGHHIkdCMXpx8wxHnQhOdcYX6zr3CucIkbZDJNOIs-rAs2yH6~d6LpF~LHJfdksPiTALKNHGsjhyzNVOnH2HyVNEki88drig8dK3chGS88eeFB1U48jnSfmQFa0Ddzq2CLYAsCIUTYzF3mAgBCSVKavPjBeCIVtt2MdqFsNVVaKJJS5Rty2cjONWMN20YICxQtB3LtX0b08wXaT5eYw787BDws11CYvfndGSznWq1um259TXi2GI9UpX-KQRJuZJubjByaRrJr0buxXnt7S8OwsjOxa-flv6To21vSsvOd2iayCBOHfWg__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA).

Cheers,
Tobias

**Comment by circR** [comment]
Hi Tobias

Thank you for your answer.
