### ISSUE TITLE
Question about RNA prep kit supported by DCC

### ISSUE THREAD

**Issue by giuseppe0525** [dieterich-lab/DCC#55]
Hi,

I  want to enquire if the RNA prep kit _**TruSeq Stranded mRNA Sample Prep Kit**_ is supported by DCC. Is there any evidence supporting this idea?

According to the chapter _**Deep Computational Circular RNA Analytics from RNA-seq**_ , the first-strand kit _TruSeq Stranded mRNA Sample Prep Kit_ is available for DCC (explained below). However, as far as I know, the TruSeq Stranded mRNA Sample Prep Kit employs poly-T oligo attached magnetic beads to purify the poly-A containing mRNA, suggesting that the cirRNAs, which lack the poly-A terminal, will be depleted with this procedure. 

> “DCC supports different sequencing protocols widely used for
> whole-transcriptome experiments.
> …
> The following list gives an overview of common
> sequencing kits and the respective parameter choice:
> First-strand kits (default):
> ●● All dUTP methods, NSR, NNSR
> ●● TruSeq Stranded Total RNA Sample Prep Kit
> ●● TruSeq Stranded mRNA Sample Prep Kit
> ●● NEB Ultra Directional RNA Library Prep Kit
> ●● Agilent SureSelect Strand-Specific”

Thank you in advance.

giuseppe

**Comment by tjakobi** [comment]
Dear @giuseppe0525,

you are correct, the "TruSeq Stranded mRNA Sample Prep Kit" should not appear in this list due to the reason you mentioned. Generally, the kit should work with total RNA and not select for poly-A, as this would filter out probably all circRNAs.

Cheers,
Tobias

**Comment by giuseppe0525** [comment]
Thanks for your answer.
