### ISSUE TITLE
Error in the DCC run 

### ISSUE THREAD

**Issue by afilipch** [dieterich-lab/DCC#6]
Dear Developers

I am Andrei Filipchyk and I try to use your tool.

While running paired-end data i got the following error. How it can be fixed. Thanks

DCC data/mates.junction -mt1 data/mate1.junction -mt2 data/mate2.junction -D -R repeat_masker.gtf -Pi -F -M  -fg -Nr 1 1

Traceback (most recent call last):
  File "/usr/local/bin/DCC", line 9, in <module>
    load_entry_point('DCC==0.3.2', 'console_scripts', 'DCC')()
  File "build/bdist.linux-x86_64/egg/DCC/main.py", line 402, in main
UnboundLocalError: local variable 'CircSkipfiles' referenced before assignment

Thanks,
Andrei

**Comment by tjakobi** [comment]
The error has been addressed in the latest commit. The problem occurred when selecting the annotate option (-A) without selecting the circ detection option (-D). This problem has been fixed.
