### ISSUE TITLE
How to download or create the "repeat.gtf"

### ISSUE THREAD

**Issue by Scathacheng** [dieterich-lab/DCC#62]
Hi there, I don't know how to download repeat.gtf in UCSC table browser, actually I can't find the right option. Or is there any way to create a repeat.GTF using existing file? Could you please tell me how to prepare this repeat.gtf. Thanks!

**Comment by Scathacheng** [comment]
all right, I think I know how to download that, thanks!

**Comment by tjakobi** [comment]
Okay, great. I'll to improve the documentation on this issue.
