### ISSUE TITLE
IOError: [Errno 2]  No such file or directory: CircRNACount

### ISSUE THREAD

**Issue by MaxHills** [dieterich-lab/DCC#66]
CircRNACount is supposed to be output by DCC, but I receive an error that it does not exist a few seconds after running DCC from the command line.

1. Command line used for the command

DCC \
@dcc_fileLists/ADAR_samplesheet \
-B @dcc_fileLists/ADAR_BAM_fileList \
-an $home/mm10/mm10.all.gtf \
-T 14 \
-M \
-Nr 2 4 \
-G \
-A $home/mm10/mm10.ucsc.fa \
-R $home/mm10/mm10.allRepeats.gtf \
-O dcc/ADAR/

2. Complete error message

Traceback (most recent call last):
  File "/home/mh2354/.local/bin/DCC", line 9, in <module>
    load_entry_point('DCC==0.4.7', 'console_scripts', 'DCC')()
  File "build/bdist.linux-x86_64/egg/DCC/main.py", line 452, in main
  File "/n/apps/CentOS7/install/pyenv-1.0.0/pyenv/versions/2.7.5/lib/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/n/apps/CentOS7/install/pyenv-1.0.0/pyenv/versions/2.7.5/lib/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
IOError: [Errno 2] No such file or directory: 'dcc/ADAR/CircRNACount'

My @samplesheet:
cat ADAR_samplesheet 
/l/Yu/YuLab/Bioinformatics/projects/mhh_CIRCexplorer2/align/starOUT/ADAR/ACTTGA/ACTTGA.Chimeric.out.junction
/l/Yu/YuLab/Bioinformatics/projects/mhh_CIRCexplorer2/align/starOUT/ADAR/CAGATC/CAGATC.Chimeric.out.junction
/l/Yu/YuLab/Bioinformatics/projects/mhh_CIRCexplorer2/align/starOUT/ADAR/CCGTCC/CCGTCC.Chimeric.out.junction
/l/Yu/YuLab/Bioinformatics/projects/mhh_CIRCexplorer2/align/starOUT/ADAR/GCCAAT/GCCAAT.Chimeric.out.junction

My @bam:
cat ADAR_BAM_fileList 
/l/Yu/YuLab/Bioinformatics/projects/mhh_CIRCexplorer2/align/starOUT/ADAR/ACTTGA/ACTTGA.Aligned.sortedByCoord.out.bam
/l/Yu/YuLab/Bioinformatics/projects/mhh_CIRCexplorer2/align/starOUT/ADAR/CAGATC/CAGATC.Aligned.sortedByCoord.out.bam
/l/Yu/YuLab/Bioinformatics/projects/mhh_CIRCexplorer2/align/starOUT/ADAR/CCGTCC/CCGTCC.Aligned.sortedByCoord.out.bam
/l/Yu/YuLab/Bioinformatics/projects/mhh_CIRCexplorer2/align/starOUT/ADAR/GCCAAT/GCCAAT.Aligned.sortedByCoord.out.bam

**Comment by tjakobi** [comment]
Hi @MaxHills,

you need to specify the `-D` flag to actually do the circRNA detection (and get the corresponding output file). 

I, on the other hand, need to make sure to check for this combination of CLI flags.

Cheers
Tobias
