### ISSUE TITLE
output files

### ISSUE THREAD

**Issue by Anbupalam** [dieterich-lab/DCC#71]
Hi 
DCC was run with the following commands for two samples.

python /data2/DCC/DCC/main.py @samplesheet -mt1 @mate1 -mt2 @mate2 -D -R /data2/Refgenome/UCSC_grch38_repeats.gtf -an /data2/Refgenome/Homo_sapiens.GRCh38.97.gtf -Pi -F -M -Nr 5 6 -fg -G -A Homo_sapiens.GRCh38.dna.primary_assembly.fa

The program completed normally but the output files are only in the temporary folder "_tmp_DCC"

-rw-rw-r-- 1 user1 user1 101234720 Nov  7 07:47 1137__ROI1_S92_R.Chimeric.out.junction.H3XX33         
-rw-rw-r-- 1 user1 user1   4311935 Nov  7 09:52 1137__ROI1_S92_R.Chimeric.out.junction.H3XX33.circRNA         
-rw-rw-r-- 1 user1 user1   7326316 Nov  7 09:52 1137__ROI1_S92_R.Chimeric.out.junction.H3XX33.circRNAmapped         
-rw-rw-r-- 1 user1 user1 107940938 Nov  7 07:48 22704__ROI1_S78_R.Chimeric.out.junction.0QXV72         
-rw-rw-r-- 1 user1 user1   4941834 Nov  7 08:50 22704__ROI1_S78_R.Chimeric.out.junction.0QXV72.circRNA         
-rw-rw-r-- 1 user1 user1   7323560 Nov  7 09:52 22704__ROI1_S78_R.Chimeric.out.junction.0QXV72.circRNAmapped         
-rw-rw-r-- 1 user1 user1   6823054 Nov  7 09:52 tmp_circCount        
-rw-rw-r-- 1 user1 user1   8456137 Nov  7 09:59 tmp_coordinates        
-rw-rw-r-- 1 user1 user1   5877569 Nov  7 09:51 tmp_duplicates.GWY7MD        
-rw-rw-r-- 1 user1 user1   3609301 Nov  7 08:50 tmp_duplicates.XN8OXV        
-rw-rw-r-- 1 user1 user1  13040015 Nov  7 09:51 tmp_findcirc.GWY7MD        
-rw-rw-r-- 1 user1 user1   9278707 Nov  7 08:50 tmp_findcirc.XN8OXV        
-rw-rw-r-- 1 user1 user1 582692510 Nov  7 09:59 tmp_Homo_sapiens.GRCh38.97.gtf.exon.sorted        
-rw-rw-r-- 1 user1 user1  87642483 Nov  7 07:47 tmp_merged        
-rw-rw-r-- 1 user1 user1  49071549 Nov  7 09:51 tmp_nonduplicates.GWY7MD        
-rw-rw-r-- 1 user1 user1  34917293 Nov  7 08:50 tmp_nonduplicates.XN8OXV        
-rw-rw-r-- 1 user1 user1  12236675 Nov  7 09:51 tmp_normalcircs.GWY7MD        
-rw-rw-r-- 1 user1 user1   8785263 Nov  7 08:50 tmp_normalcircs.XN8OXV        
-rw-rw-r-- 1 user1 user1  54949462 Nov  7 07:48 tmp_printcirclines.GWY7MD        
-rw-rw-r-- 1 user1 user1  38526594 Nov  7 07:48 tmp_printcirclines.XN8OXV        
-rw-rw-r-- 1 user1 user1    803340 Nov  7 09:51 tmp_smallcircs.GWY7MD        
-rw-rw-r-- 1 user1 user1    493444 Nov  7 08:50 tmp_smallcircs.XN8OXV        
-rw-rw-r-- 1 user1 user1   8933322 Nov  7 07:47 tmp_twochimera        

I don't see the LinearCount and CircSkipJunctions files in the folder. 
Please advise.

**Comment by Anbupalam** [comment]
Hi 
I am able to fix this issue.

**Comment by tjakobi** [comment]
Hi @Anbupalam,

just for clarification and for future reference, how did you solve the issue?

Cheers,
Tobias

**Comment by Anbupalam** [comment]
Hi Tobias,

Sorry for the late reply.

I forgot to generate the *.bai index files for the *.bam files In my
original  submission. With the index files in the right folder the program
produced all the relevant output files.

Thanks
Anbu.

**Comment by tjakobi** [comment]
Hi @Anbupalam,

thank you for your feedback. I wonder why this even happens... there is a check to make sure all BAM files habe an index:

https://github.com/dieterich-lab/DCC/blame/68797f3e456d65cafd51ff20e93dd9ea0d45e765/DCC/main.py#L725

Would you have the complete log file of this run? Are you sure it terminated with status 0?

Cheers,
Tobias

**Comment by Anbupalam** [comment]
Sorry, I don't have the log file now. I had to cleanup due to storage
limitations. As it was run on cluster computer with job-submission, I only
looked at the job exit status and I remember the exit status was OK but
probably the log file would have reflected this issue.

Thanks
Anbu.

**Comment by tjakobi** [comment]
Hi @Anbupalam,

okay, thank your for coming back to me. 

I'll see if there might be any issue with the index detection.

Cheers,
Tobias
