### ISSUE TITLE
 how does -L, --Ln filter works?

### ISSUE THREAD

**Issue by gabee-chan** [dieterich-lab/DCC#77]
Hi

I was looking through the supplementary file in your paper and found that the --L (--Ln) option you used 20 instead of 50 as the default parameter. I was wondering if you could explain further how this parameter works? Does it removes potential circRNAs associated to repeat regions of length --L according to the GTF of repeat regions ?

Thanks

**Comment by tjakobi** [comment]
Dear @gabee-chan ,

some of the parameters were tuned after the initial release as we worked on more data sets. In essence, the parameter gives the maximum amount of the circRNA that may overlap with a repeat region. E.g. if `-L 50` then if left or right end of the circRNA overlap with more than 50 bp with a known repeat region the circRNA would be discarded. 

Cheers,
Tobias
