### ISSUE TITLE
-Nr option

### ISSUE THREAD

**Issue by EricSHo** [dieterich-lab/DCC#79]
DCC 0.4.8 ubuntu 

I have a question about the -Nr option of DCC.

The Westholm data example used -Nr 5 6. The comment said "minimum count in one replicate [1] and number of replicates the candidate has to be detected in [2]" I don't get what do [1] and [2] mean? 

Do they mean the following?
1. At least 5 junction reads per back-splicing site in a sample, and
2. This back-splicing site must be detected in at least 6 replicates

Thanks, Eric.

**Comment by tjakobi** [comment]
Hi @EricSHo,

it's kind of both: 

`-Nr 5,6`: at least 5 BSJ counts in at least 6 samples 

Does this help?

Cheers,
Tobias

**Comment by EricSHo** [comment]
I need further clarification. How many BSJ in your example, 5 or 5x6=30?

**Comment by tjakobi** [comment]
Speaking of overall BSJ reads it would be 30, since in each of the 6 samples we require 5 reads (and the samples have independent read sets).
