### ISSUE TITLE
Grouping of samples and replicates

### ISSUE THREAD

**Issue by EricSHo** [dieterich-lab/DCC#80]
Hi,

My installation is DCC 0.4.8 ubuntu

I have a question about the grouping of samples of replicates.

My data consists of 4 experimental conditions, and 3 replicates per condition.

Should I specify all 4x3=12 Chimeric.out.junction entries in one samplesheet/mate1/mate2? In this case, I run DCC only once.

Or, should I create 4 separate samplesheets/mate1s/mate2s, one for each condition, and each contains 3 replicates? In this case, I need to run DCC 4 times.

Thanks, Eric.

**Comment by tjakobi** [comment]
Hi @EricSHo,

generally you can run everything together and later on pull only those circRNAs that are specific for one condition. When you want to use circtest in the next step having a combined table will also make that step easier.

Cheers,
Tobias
