### ISSUE TITLE
small issues for bowtie2, star index missing GTF ect

### ISSUE THREAD

**Issue by xiongxxp** [dieterich-lab/DCC#81]
Hi Tobias,
Very nice tool for circular RNA study. I am trying this tool and met some issues. Generally, I follow the method described in your paper  "Deep Computational Circular RNA Analytics from RNA-seq Data". But I met some issues.
1. When I run this following command, the running results keep printing out on my screen. If add >nohup.log command,  the write-in nohup.log will be quite big.
![image](https://user-images.githubusercontent.com/52878331/85809464-d3da2180-b70c-11ea-92c7-75d2b7b33c71.png)
2. 
![image](https://user-images.githubusercontent.com/52878331/85809629-71cdec00-b70d-11ea-80c4-3b542c895851.png)
looks like there is no GTF in the code of method. Is it normal or typo? I modified it and added the GTF file for building index.
3. 
![image](https://user-images.githubusercontent.com/52878331/85809677-8d38f700-b70d-11ea-9c10-d29dde6c307e.png)
![image](https://user-images.githubusercontent.com/52878331/85809800-e86ae980-b70d-11ea-806e-63fe6e43ef95.png)
In this step, the paper recommends getting a GTF file from the UCSC Browser. But the browser only allows select either RepeatMasker or Simple Repeats, how do I choose both of them?
4. When I try to test multiple samples, there is a problem with linearCount file. All of the samples will get the same counts.
![image](https://user-images.githubusercontent.com/52878331/85809965-6cbd6c80-b70e-11ea-9efc-8322521d5ad1.png)
![image](https://user-images.githubusercontent.com/52878331/85810054-aaba9080-b70e-11ea-9634-13fedacaa6b7.png)

Thank you for your help.
Best,
Xiong

**Comment by tjakobi** [comment]
> Hi Tobias,
> Very nice tool for circular RNA study. I am trying this tool and met some issues. Generally, I follow the method described in your paper "Deep Computational Circular RNA Analytics from RNA-seq Data". But I met some issues.

Hi @xiongxxp,

thank you for using circtools!

> 1. When I run this following command, the running results keep printing out on my screen. If add >nohup.log command,  the write-in nohup.log will be quite big.
>    ![image](https://user-images.githubusercontent.com/52878331/85809464-d3da2180-b70c-11ea-92c7-75d2b7b33c71.png)

I see. It seems the `-S` option of bowtie2 is missing. Please add `-S /devn/null` to your command line. This will pipe aligned reads to the system's null device.

> ![image](https://user-images.githubusercontent.com/52878331/85809629-71cdec00-b70d-11ea-80c4-3b542c895851.png)
> looks like there is no GTF in the code of method. Is it normal or typo? I modified it and added the GTF file for building index.

The GTF file is used by STAR for spliced alignments and by DCC for gene annotation if that is what you mean.
> 3.
> ![image](https://user-images.githubusercontent.com/52878331/85809677-8d38f700-b70d-11ea-9c10-d29dde6c307e.png)
> ![image](https://user-images.githubusercontent.com/52878331/85809800-e86ae980-b70d-11ea-806e-63fe6e43ef95.png)
> In this step, the paper recommends getting a GTF file from the UCSC Browser. But the browser only allows select either RepeatMasker or Simple Repeats, how do I choose both of them?

You should use Repeat Masker.In the next step you should be able to choose between BED and GTF file format for export. 

> 4. When I try to test multiple samples, there is a problem with linearCount file. All of the samples will get the same counts.
> ![image](https://user-images.githubusercontent.com/52878331/85809965-6cbd6c80-b70e-11ea-9efc-8322521d5ad1.png)
> ![image](https://user-images.githubusercontent.com/52878331/85810054-aaba9080-b70e-11ea-9634-13fedacaa6b7.png)

That looks like you're always using the same BAM file for all samples. How do your BAM file list, and all other input files of DCC look like? I see you are not using `-B` to supply the BAM files - you should do that, otherwise DCC might guess the BAM files wrong. 

> Thank you for your help.
> Best,
> Xiong

Cheers,
Tobias
