### ISSUE TITLE
Normalization of read 

### ISSUE THREAD

**Issue by aashishps** [dieterich-lab/DCC#86]
can anyone please tell about is DCC provides normalised reads if not then how to normalise them and how to do differential expression analysis of circRNA.

**Comment by tjakobi** [comment]
Dear @aashishps,

DCC provides not normalized raw counts of splice junction and linear read counts.

For normalization you might use the edgeR R package which can also be used for differential expression analysis. 

Another option would be www.github.com/dieterich-lab/circtest which is able to compare circRNA expression in two (or more) different conditions. 

Cheers,
Tobias
