### ISSUE TITLE
`Start-End` not assigned correctly

### ISSUE THREAD

**Issue by gnilihzeux** [dieterich-lab/DCC#87]
Dear author,
    I found the `start-end` feature of a circRNA not assigned correctly. Details is as follows:

**circRNA** chr1_111724942_111725414_+
**DCC** intron-exon
**Should be** intron-intron

Actually, this circRNA is very close to a exon with just 2 bp.

My configures is as follows:
```
GTF: genecode grch37 p13
DCC version: 0.4.7
```
Thanks.

**Comment by tjakobi** [comment]
Dear @gnilihzeux,

is it possible, that the annotated gene has multiple isoforms with different exon/intron borders?

DCC tries to merge different transcript per gene for the annotation process, but borderline cases like yours might stem from two transcripts with slightly shifted borders, i.e. the annotation is correct for one transcript but not for the other one.

Cheers,
Tobias

**Comment by gnilihzeux** [comment]
Thanks, @tjakobi . Just like you said.
