### ISSUE TITLE
Could DCC get f-circRNA ?

### ISSUE THREAD

**Issue by gnilihzeux** [dieterich-lab/DCC#88]
Dear author,

  It's ok for DCC to detect some circRNAs within multiple genes, 
but could it work for **inter-chromsomes circRNAs**, like those derived from fusion-genes such as PAX3-FOXO1?

   BTW, I'd found a specialized program **Fcirc** for f-circRNA.
   
   Thanks.

**Comment by tjakobi** [comment]
Dear @gnilihzeux,

thank you for your interest in DCC.

DCC was not designed for the purpose you outlined.

Inter-chromsomes circRNAs should be automatically filtered out by DCC if they are recognized as those. 

You might be able to see fusion candidates when not using `-fg` filter option, but I have doubts that this would work between different chromosomes.

Fcirc in this case might be the better choice.

Cheers,
Tobias

**Comment by gnilihzeux** [comment]
Thank you. I'd try another tool **fcirc**.
