### ISSUE TITLE
Error in DCC running : missing file even after providing the file .

### ISSUE THREAD

**Issue by manzaaa** [dieterich-lab/DCC#89]
Hello,
It is a very good tool for circRNA detection. I am trying to use this tool and I'm running into an error. It would be great if you could help me with it. I mapped my reads to the reference genome using STAR and got the chimeric.out.junction and used it as the input for DCC. I used the following command 

DCC --detect @female_heartChimeric.out.junction -R repeatmasker_human.gtf  -an hg38.ensGene.gtf  -B female_heartAligned_sorted.bam  -F -M -Nr 5 6 -fg -G -A hg38.fa 

This is the error I keep getting:

ERROR: Required file chr2	88111677	-	chr12	122328366	+	-1	0	0	D93Z3NS1:226:C75WFACXX:2:1101:2637:45497	88111678	101M	122328367	60M4560N41M is missing, exiting

Is it because of the repeat file or the annotation file ? I am not able to figure it out. 

Thanks for your time
Maanasa

**Comment by tjakobi** [comment]
Dear @manzaaa,

when providing the `@female_heartChimeric.out.junction` option, DCC treat every line of the file `female_heartChimeric.out.junction` as a file name and try to topen that file. 

The correct call would be something like
```
DCC --detect female_heartChimeric.out.junction -R repeatmasker_human.gtf -an hg38.ensGene.gtf -B female_heartAligned_sorted.bam -F -M -Nr 5 6 -fg -G -A hg38.fa
```

Cheers,
Tobias

**Comment by manzaaa** [comment]
Dear Tobias,

Thank you so much for the explanation. Was able to get it  running!

Cheers,
Maanasa
