### ISSUE TITLE
Single end reads and function checkjunctionfiles

### ISSUE THREAD

**Issue by CDieterich** [dieterich-lab/DCC#9]
if checkjunctionfiles(options.Input, options.mate1, options.mate2):
        logging.info("circRNA detection skipped due to empty junction files")
        print("circRNA detection skipped due to empty junction files")

Please make sure that the software works even if options.mate1 and options.mate2
are not given (i.e. single end sequencing)

**Comment by CDieterich** [comment]
BTW,

 File "build/bdist.linux-x86_64/egg/DCC/main.py", line 451, in checkjunctionfiles
TypeError: object of type 'NoneType' has no len()

**Comment by CDieterich** [comment]
File "build/bdist.linux-x86_64/egg/DCC/main.py", line 451, in checkjunctionfiles
TypeError: object of type 'NoneType' has no len()

**Comment by tjakobi** [comment]
Thank your for reporting the issue.
The issue was addressed in the new release 0.3.4.
