### ISSUE TITLE
circFilter.py need more than 8 values to unpack

### ISSUE THREAD

**Issue by yemao701** [dieterich-lab/DCC#91]
When I ran DCC, I encounterd this warning, can you help me with this problem? Thank you!

![QQ截图20210201195409](https://user-images.githubusercontent.com/63441746/106455514-442cfa80-64c7-11eb-928d-1deb4fc86cf5.jpg)

**Comment by tjakobi** [comment]
The repeat file you are supplying seems not to be formatted correctly. 

Could you paste the first 50 lines of the repeat file?

**Comment by yemao701** [comment]
Thank you for your timely response!
Here are a few lines of my repeat file

chr10   TRF     exon    1       49      55      +       gene_id "TR0000001";
chr10   TRF     exon    1       49      64      +       gene_id "TR0000002";
chr10   TRF     exon    2866    2938    101     +       gene_id "TR0000003";
chr10   TRF     exon    3521    3563    86      +       gene_id "TR0000004";
chr10   TRF     exon    11806   11835   51      +       gene_id "TR0000005";
chr10   TRF     exon    14792   14832   64      +       gene_id "TR0000006";
chr10   TRF     exon    26371   26405   63      +       gene_id "TR0000007";
chr10   TRF     exon    29523   29551   58      +       gene_id "TR0000008";
chr10   TRF     exon    31484   31692   409     +       gene_id "TR0000009";
chr10   TRF     exon    33143   33167   50      +       gene_id "TR0000010";
chr10   TRF     exon    34030   34060   62      +       gene_id "TR0000011";
chr10   TRF     exon    34544   34582   55      +       gene_id "TR0000012";
chr10   TRF     exon    37933   37996   119     +       gene_id "TR0000013";
chr10   TRF     exon    39153   39185   50      +       gene_id "TR0000014";
chr10   TRF     exon    40851   40892   57      +       gene_id "TR0000015";
chr10   TRF     exon    43143   43167   50      +       gene_id "TR0000016";
chr10   TRF     exon    51177   51216   71      +       gene_id "TR0000017";
chr10   TRF     exon    59764   59798   70      +       gene_id "TR0000018";
chr10   TRF     exon    65692   65720   51      +       gene_id "TR0000019";
chr10   TRF     exon    65898   65932   70      +       gene_id "TR0000020";
chr10   TRF     exon    65932   65964   66      +       gene_id "TR0000021";
chr10   TRF     exon    67434   67517   150     +       gene_id "TR0000022";
chr10   TRF     exon    72959   72984   52      +       gene_id "TR0000023";
chr10   TRF     exon    96988   97020   66      +       gene_id "TR0000024";
chr10   TRF     exon    106974  107002  58      +       gene_id "TR0000025";
chr10   TRF     exon    115971  116017  67      +       gene_id "TR0000026";
chr10   TRF     exon    118965  118996  57      +       gene_id "TR0000027";
chr10   TRF     exon    124420  124460  82      +       gene_id "TR0000028";
chr10   TRF     exon    124714  124752  78      +       gene_id "TR0000029";
chr10   TRF     exon    127650  127680  53      +       gene_id "TR0000030";
chr10   TRF     exon    128802  128844  79      +       gene_id "TR0000031";
chr10   TRF     exon    136332  136372  73      +       gene_id "TR0000032";
chr10   TRF     exon    143827  143879  63      +       gene_id "TR0000033";
chr10   TRF     exon    151258  151317  111     +       gene_id "TR0000034";
chr10   TRF     exon    154951  154976  52      +       gene_id "TR0000035";
chr10   TRF     exon    160349  160380  55      +       gene_id "TR0000036";
chr10   TRF     exon    169740  169777  76      +       gene_id "TR0000037";
chr10   TRF     exon    170323  170375  72      +       gene_id "TR0000038";
chr10   TRF     exon    178159  178201  61      +       gene_id "TR0000039";
chr10   TRF     exon    180519  180599  110     +       gene_id "TR0000040";
chr10   TRF     exon    187792  187828  60      +       gene_id "TR0000041";
chr10   TRF     exon    188311  188335  50      +       gene_id "TR0000042";
chr10   TRF     exon    204218  204251  68      +       gene_id "TR0000043";
chr10   TRF     exon    210393  210417  50      +       gene_id "TR0000044";

**Comment by tjakobi** [comment]
If those columns are tab separated that looks fine.

Is there any way you could upload the complete file somewhere? Some lines seems to have more than 8 columns.
