### ISSUE TITLE
ERROR: Required file detect is missing, exiting

### ISSUE THREAD

**Issue by semiramisgh** [dieterich-lab/DCC#94]
when I am going to run my bash script "circtools detect ", I get this error:  Required file detect is missing, exiting. 
 The following is my bash code which is the same as the manual.
 circtools detect @samplesheet -D -B @bam_file_list -R GRCm38_90_repeatmasker.gtf -an Mus_musculus.GRCm38.101.gtf -F -Nr 5 6 -M -fg -G -A Mus_musculus.GRCm38.dna.primary_assembly.fa 

@samplesheet is a file name including all the paths for chimeric.out.junction files for multiple samples.
@bam_file_list is a file name including all the paths .bam files 
I also tried without -B flag and some other options but still, I get the same error!
I am wondering which file is missing, and why detect module is not working with adding paths directly without using @flag.

Thank you in advance!

**Comment by tjakobi** [comment]
Dear @semiramisgh,

for some reason circtools seems to try to load a file named `detect`.

Just to start with the basics, what does `circtools detect --version` return?
