### ISSUE TITLE
detect module doesnt work!

### ISSUE THREAD

**Issue by semiramisgh** [dieterich-lab/DCC#95]
I am running circtools on my dataset to detect circRNAs. I have prepared input files like : .bam .bam.bai and all .junction files but unfortunately after many tries and errors still it fails with this error: required detect file is missing. 

circtools detect @samplesheet 
samplesheet is a file name including all junction file paths. 

could you please help me to figure out what is wrong?

**Comment by tjakobi** [comment]
Dear @semiramisgh,

thank your for using DCC and sorry for the late response.

Could you please paste the contents of the samplesheet file as well as other input files? 

Moreover, could you please provide the complete command line for DCC?
