### ISSUE TITLE
The meaning of warning message

### ISSUE THREAD

**Issue by m-kouhsar** [dieterich-lab/DCC#97]
Hi
I ran the DCC for some paired-end data based on the user guide. It works properly and is completed successfully, but in  the log file there are many warning messages like this:

WARNING: circRNA end position ('chr3', '113162019') does not have mapped read counts, treated as 0

What does mean this warning message? 
Does this message mean DCC sets the count to zero for those circRNAs which they don't have any linear read mapped to the genome? 
another question is: Do DCC detect novel circRNAs? I need to predict all circRNAs in my data (both novel and annotated). Are there any options that should be set to do this?

Best
Morteza

**Comment by tjakobi** [comment]
Hi @m-kouhsar,

Your assumption is correct in that the message means that no linear reads have been mapped to the circRNA position. However, the "treating as 0" refers to the LinearCount file, not the CircRNACount file.

To answer your second question, yes, DCC predicts novel circRNAs automatically, the annotation is purely used for the assignment to gene names.

Cheers,

Tobias

**Comment by m-kouhsar** [comment]
Thanks, Tobias
