### ISSUE TITLE
Missing  LinearCount and CircSkipJunctions files

### ISSUE THREAD

**Issue by mumichae** [dieterich-lab/DCC#98]
**Describe the bug**
More a question than a bug.
When I specify `-D` and `-G`, I don't get `LinearCount` or `CircSkipJunctions`, even though all necessary files were provided. Is this a bug or am I missing something?

**To Reproduce**
```
$OUT_DIR=output
DCC Chimeric.out.junction \
  --mate1 mate1_Chimeric.out.junction --mate2 mate2_Chimeric.out.junction \
  --annotation gencode.v38.annotation.gtf \
  --bam Aligned.sortedByCoord.out.bam \
  --refseq hg38.fa
  --D -G --chrM --rep_file repeats_hg38.gtf.gz \
  --output $OUT_DIR --temp $OUT_DIR/tmp --threads 5
```

Conda environment YAML
```
name: DCC
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.8
  - pip
  - HTSeq
  - pysam
  - numpy
  - pandas
  - pip:
    - https://github.com/dieterich-lab/DCC/archive/refs/tags/v0.5.0.tar.gz
```

**Desktop:**

 - OS: CentOS
 - Python version 3.8.12
 - Version 0.5.0

**Comment by tjakobi** [comment]
Hi @mumichae,

Your command line seems good, but given that you provide mate1+2, you should specify `-Pi`. There might be an issue checking the flags accordingly. 

Let me know is that helps.

Cheers,
Tobias

**Comment by mumichae** [comment]
Hi Tobias,

Thanks a lot! I must have missed that one, now it works!

Best,
Michaela
